name: Build and Deploy Angular Microfrontend

on:
  push:
    branches:
      - main # Runs workflow on push to main branch
  pull_request:
    branches:
      - main # Runs workflow on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # Ensure this matches your Angular version

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: Upload Artifact (for Deployment)
        uses: actions/upload-artifact@v4
        with:
          name: angular-build
          path: dist/ # Path where Angular builds the app

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          path: dist/

      # Deployment (Choose One: GitHub Pages, AWS S3, Firebase, Vercel, Docker)

      - name: Deploy to GitHub Pages (Optional)
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/
